#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs = " -r irb/completion"
libs << " -r lib/tagooru.rb"

exec "#{irb} #{libs} --simple-prompt"
